name: Build the page
on:
  push:
    branches-ignore:
      - master
jobs:
  Build_Page:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: make dep
      - run: make page
